services:
  - type: web
    name: flask-downloader
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    autoDeploy: true
    envVars:
      - key: LOCATION
        value: "/downloads"
    mounts:
      - type: volume
        name: downloads
        path: /downloads
